# -*- yaml -*-
#
# michael a.g. aïvázis
# orthologue
# (c) 1998-2020 all rights reserved
#

dist: focal
group: travis_latest

language: python
python:
  - 3.8

addons:
  apt:
    packages:
      - python3.8-dev
      - libgsl-dev
      - python3-pybind11

install:
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-fsized-deallocation"
  - make install

script:
  - ctest --verbose

# end of file
