#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


# support
import os


# colors that pyre uses but that are not part of the canonical X11 set
extras = [
    ("amber", 255, 191, 0),
    ("sage", 176, 208, 176),
]


def entries():
    """
    Read the canonical color file and yield one C++ table entry per color name
    """
    # the canonical color file sits next to this script
    source = os.path.join(os.path.dirname(__file__), "rgb.txt")
    # go through its lines, keeping every name so any consumer's spelling resolves
    for line in open(source):
        # pull the three channels and the color name
        red, green, blue, name = line.strip().split(None, 3)
        # normalize the channels from bytes to the unit interval
        r, g, b = int(red) / 255, int(green) / 255, int(blue) / 255
        # emit the entry as a name paired with its {rgb_t}
        yield f'    {{ "{name}", {{ {r:.6f}f, {g:.6f}f, {b:.6f}f }} }},'
    # then pyre's own colors
    for name, red, green, blue in extras:
        # normalized the same way
        r, g, b = red / 255, green / 255, blue / 255
        # emitted the same way
        yield f'    {{ "{name}", {{ {r:.6f}f, {g:.6f}f, {b:.6f}f }} }},'


def preamble(count):
    """
    The opening lines of the generated header, sized to hold {count} entries
    """
    # the fixed header, includes, and the table declaration
    return f"""// -*- c++ -*-
//
// michael a.g. aïvázis <michael.aivazis@para-sim.com>
// (c) 1998-2026 all rights reserved
//
// this file is generated by {{etc/autogen/rgb_chroma.py}} from {{rgb.txt}}; do not edit by hand

#pragma once


// the {{rgb_t}} type these entries hold
#include "../forward.h"

// externals
// {{std::array}} holds the table
#include <array>
// {{std::string_view}} keys avoid any per-entry allocation
#include <string_view>
// {{std::optional}} carries the result of a lookup that may miss
#include <optional>


// the table of color names to {{rgb}} triplets: every X11 name, plus pyre's custom colors
namespace pyre::chroma::rgb::palette {{
    // an entry pairs a color name with the color it denotes
    struct entry_t {{
        // the name
        std::string_view name;
        // the color
        rgb_t color;
    }};

    // the table itself
    inline constexpr std::array<entry_t, {count}> table = {{ {{"""


def postamble():
    """
    The closing lines: the end of the table and the lookup function
    """
    # close the table, then define the name lookup
    return """    } };

    // look up a color by name; empty when the name is not in the table
    inline auto
    find(std::string_view name) -> std::optional<rgb_t>
    {
        // scan the table for a matching name
        for (const auto & entry : table) {
            // when the name matches
            if (entry.name == name) {
                // hand back its color
                return entry.color;
            }
        }
        // otherwise report the miss
        return std::nullopt;
    }
} // namespace pyre::chroma::rgb::palette


// end of file"""


# bootstrap
if __name__ == "__main__":
    # collect the entries
    rows = list(entries())
    # the destination header lives in the chroma library tree
    here = os.path.dirname(__file__)
    destination = os.path.join(here, "..", "..", "lib", "chroma", "rgb", "palette.h")
    # write it out
    with open(destination, "w") as palette:
        # the preamble is sized to the number of entries we kept
        print(preamble(len(rows)), file=palette)
        # then the entries themselves
        print("\n".join(rows), file=palette)
        # and the closing lines
        print(postamble(), file=palette)


# end of file
