# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis
# california institute of technology
# (c) 1998-2010 all rights reserved
#


# exceptions
from ..framework.exceptions import FrameworkError


class UnitError(FrameworkError):
    """
    Base class for all errors generated by this package
    """


    def __init__(self, msg, **kwds):
        super().__init__(**kwds)
        self.msg = msg
        return

    def __str__(self):
        return self.msg


# end of file 
