# -*- Python -*-
# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


# externals
import os
import time

# the device base class of whichever implementation is live, so the chronicler accepts me
from . import device

# the wire form of an entry
from .Record import Record


# ship entries to another process
class Courier(device):
    """
    Journal device that writes entries, as records, to a file descriptor

    The far end of the descriptor is somebody else's concern: a parent process, a server,
    a daemon. This device never blocks and never raises: the descriptor is non-blocking, a
    record that cannot be written whole is dropped whole, drops are counted and reported
    once the far end catches up, and a far end that has gone away silences the courier
    """

    # constants
    # the channel on which drops are reported
    reporter = "journal.courier"

    # interface
    def alert(self, entry):
        """
        Generate an alert

        Alerts are user-facing; they are generated by {info}, {warning}, and {error}
        """
        # deliver
        return self._deliver(entry=entry, sink="alert")

    def help(self, entry):
        """
        Generate a help screen
        """
        # deliver
        return self._deliver(entry=entry, sink="help")

    def memo(self, entry):
        """
        Issue a memo

        Memos are developer-facing; they are generated by {debug} and {firewall}
        """
        # deliver
        return self._deliver(entry=entry, sink="memo")

    def close(self):
        """
        Release the descriptor; nothing is delivered after this
        """
        # if the descriptor is still mine
        if not self.dead:
            # attempt to
            try:
                # release it
                os.close(self.descriptor)
            # if the descriptor was already gone
            except OSError:
                # there is nothing to release
                pass
            # either way, i'm done
            self.dead = True
        # all done
        return self

    # the pipeline
    def ship(self, entry, sink):
        """
        Convert {entry} into a record bound for {sink} and write it to the descriptor
        """
        # if the far end has gone away
        if self.dead:
            # there is nothing to do
            return
        # finish writing whatever was left over from the last time
        if not self._drain():
            # the far end is still not keeping up, so this entry is lost
            self._lose()
            # all done
            return
        # if records were lost since the last successful write
        if self.dropped:
            # say so, on my own channel; the report takes the sequence number ahead of the
            # entry that prompted it, since it goes out first
            notice = self.notice(entry=entry)
            # if the notice could not be written
            if not self._write(data=notice.encode()):
                # the entry that prompted it is lost as well
                self._lose()
                # all done
                return
            # the drops have been reported
            self.dropped = 0
            # if the notice went out only in part
            if self.pending:
                # the entry must not overtake its tail, so it is lost as well
                self._lose()
                # all done
                return
        # stamp the record
        record = self.stamp(entry=entry, sink=sink)
        # write it
        if self._write(data=record.encode()):
            # it is on its way
            self.shipped += 1
        # otherwise
        else:
            # it is lost
            self.dropped += 1
        # all done
        return

    def stamp(self, entry, sink):
        """
        Build the record for {entry} bound for {sink} and assign it the next sequence number
        """
        # advance the sequence
        self.seq += 1
        # stamp the record
        return Record.stamp(entry=entry, sink=sink, seq=self.seq)

    def notice(self, entry):
        """
        Build the record that reports the entries dropped since the last successful write

        The count rides in the notes, so a consumer can show it without parsing prose
        """
        # advance the sequence
        self.seq += 1
        # the drop count
        dropped = self.dropped
        # the notes: my channel, the severity, the count, and the application of the entry
        # whose delivery prompted the report, so the notice stays attributable
        notes = {
            "channel": self.reporter,
            "severity": "warning",
            "dropped": str(dropped),
        }
        # attempt to
        try:
            # copy the application name
            notes["application"] = str(entry.notes["application"])
        # if the entry doesn't carry one
        except (KeyError, TypeError):
            # leave it out
            pass
        # build the record
        return Record(
            sink="alert",
            page=[f"{dropped} journal entries were dropped"],
            notes=notes,
            seq=self.seq,
            pid=os.getpid(),
            time=time.time(),
        )

    # metamethods
    def __init__(self, descriptor, name="courier", mirror=None, **kwds):
        # chain up
        super().__init__(name=name, **kwds)
        # the descriptor is never allowed to block the process that is logging
        os.set_blocking(descriptor, False)
        # save it
        self.descriptor = descriptor
        # and the device that also gets every entry, if any
        self.mirror = mirror
        # the sequence number of the last record stamped
        self.seq = 0
        # the number of records that made it out
        self.shipped = 0
        # the number of records lost since the last successful write
        self.dropped = 0
        # the tail of a record the descriptor did not accept whole
        self.pending = b""
        # whether the far end has gone away
        self.dead = False
        # all done
        return

    # implementation details
    def _lose(self):
        """
        Account for an entry that never made it out

        It consumes a sequence number all the same, so a consumer can tell how many records it
        never saw by the gaps in the sequence
        """
        # advance the sequence
        self.seq += 1
        # and count the loss
        self.dropped += 1
        # all done
        return

    def _deliver(self, entry, sink):
        """
        Hand {entry} to the mirror, then ship it
        """
        # if there is a mirror
        if self.mirror is not None:
            # it gets the entry unchanged, through the same sink
            getattr(self.mirror, sink)(entry=entry)
        # ship it
        self.ship(entry=entry, sink=sink)
        # all done
        return self

    def _drain(self):
        """
        Attempt to finish writing the pending tail; report whether the descriptor is clear
        """
        # if there is nothing pending
        if not self.pending:
            # the descriptor is clear
            return True
        # take the tail
        data = self.pending
        # and clear it, so the write can put back whatever remains
        self.pending = b""
        # if the descriptor accepted none of it
        if not self._write(data=data):
            # it is still pending, in full
            self.pending = data
            # and the descriptor is not clear
            return False
        # the descriptor is clear only if nothing remains
        return not self.pending

    def _write(self, data):
        """
        Write {data} without blocking; report whether the descriptor accepted any of it

        A part the descriptor did not take stays pending, so records are never torn
        """
        # attempt to
        try:
            # write as much as the descriptor will take
            count = os.write(self.descriptor, data)
        # if it will take nothing right now
        except BlockingIOError:
            # report the refusal
            return False
        # if the descriptor is gone
        except OSError:
            # the far end went away; go quiet
            self.dead = True
            # nothing was accepted
            return False
        # if the descriptor took only part of the data
        if count < len(data):
            # the rest waits for the next opportunity
            self.pending = data[count:]
        # the data was accepted
        return True


# end of file
