# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis
# california institute of technology
# (c) 1998-2010 all rights reserved
#


import sys
from ..Codec import Codec


class Importer(Codec):
    """
    This package contains the implementation of the native importer
    """


    # constants
    encoding = "import"


    # interface
    def decode(self, source, locator=None):
        """
        Interpret {source} as a module to be imported
        """
        # import the module
        try:
            module = __import__(source)
        except ImportError as error:
            raise self.DecodingError(
                codec=self, uri=source, locator=locator, description=str(error)) from error
        # now look it up in the list of modules and return it
        return sys.modules[source]


    def retrieveSymbol(self, shelf, symbol):
        """
        Retrieve {symbol} from {shelf}, a symbol table previously generated by this codec
        """
        try:
            return getattr(shelf, symbol)
        except AttributeError as error:
            raise self.SymbolNotFoundError(codec=self, shelf=shelf, symbol=symbol) from error


# end of file
