# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis
# california institute of technology
# (c) 1998-2010 all rights reserved
#


# exceptions
from ..framework.exceptions import FrameworkError


class SchemaError(FrameworkError):
    """
    Base class for all errors generated by this package
    """


class CastingError(SchemaError):
    """
    Exception raised on failed attempts to convert a value to one of the supported types
    """

    def __init__(self, value, **kwds):
        super().__init__(**kwds)
        self.value = value
        return


# end of file 
