# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis
# california institute of technology
# (c) 1998-2012 all rights reserved
#

"""
Definitions for all the exceptions raised by this package
"""


from ..framework.exceptions import FrameworkError


class GenericError(FrameworkError):
    """
    Base class for all errors in this package

    Can be used as a catchall when detecting errors generated by this package
    """


class DirectoryListingError(GenericError):
    """
    Exception raised when something goes wrong with listing the contents of a local directory
    """

    def __init__(self, uri, error, **kwds):
        msg = "error while accessing {0.uri!r}: {0.error}"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        self.error = error
        return


class MountPointError(GenericError):
    """
    Exception generated when the root of a filesystem is invalid
    """

    def __init__(self, uri, error):
        msg = "error while mounting {0.uri!r}: {0.error}"
        super().__init__(description=msg)
        self.uri = uri
        self.error = error
        return


class FilesystemError(GenericError):
    """
    Base class for all filesystem errors

    Can be used as a catchall when detecting filesystem related exceptions
    """

    def __init__(self, filesystem, node, **kwds):
        super().__init__(**kwds)
        self.filesystem = filesystem
        self.node = node
        return


class NotFoundError(FilesystemError):
    """
    Exception raised when attempting to find a node and the supplied URI does not exist
    """

    def __init__(self, uri, fragment, **kwds):
        msg = "while looking for {0.uri!r}: {0.fragment!r} not found"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        self.fragment = fragment
        return


class SourceNotFoundError(FilesystemError):
    """
    Exception raised when attempting to find a node and the supplied URI does not exist
    """

    def __init__(self, uri, **kwds):
        msg = "while looking for {0.uri!r}: file not found"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        return


class FolderError(FilesystemError):
    """
    Exception raised when a request is made for the contents of a node that is not a folder
    """

    def __init__(self, uri, fragment, **kwds):
        msg = "while looking for {0.uri!r}: {0.fragment!r} is not a folder"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        self.fragment = fragment
        return


class IsFolderError(FilesystemError):
    """
    Exception raised when a request is made to open a folder
    """

    def __init__(self, uri, **kwds):
        msg = "while opening {0.uri!r}: can't open; it is a folder"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        return


class FolderInsertionError(FilesystemError):
    """
    Exception raised when attempting to insert a node in a filsystem and the target node is not
    a folder
    """

    def __init__(self, uri, target, **kwds):
        msg = "error while inserting {0.uri!r}: {0.target!r} is not a folder"
        super().__init__(description=msg, **kwds)
        self.uri = uri
        self.target = target
        return


class URISpecificationError(GenericError):
    """
    Exception raised when the supplied uri cannot be decoded
    """

    def __init__(self, uri, reason, **kwds):
        msg = "{0.uri!r}: {0.reason}"
        super().__init__(description=msg , **kwds)
        self.uri = uri
        self.reason = reason
        return


# end of file 
