# -*- cmake -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


#
# journal bindings
#
pyre_test_python_testcase(tests/journal.ext/api_application.py)
pyre_test_python_testcase(tests/journal.ext/api_file.py)
pyre_test_python_testcase(tests/journal.ext/api_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/api_quiet.py)
pyre_test_python_testcase(tests/journal.ext/cerr.py)
pyre_test_python_testcase(tests/journal.ext/chronicler.py)
pyre_test_python_testcase(tests/journal.ext/chronicler_device.py)
pyre_test_python_testcase(tests/journal.ext/courier_cxx.py)
pyre_test_python_testcase(tests/journal.ext/chronicler_meta.py)
pyre_test_python_testcase(tests/journal.ext/chronicler_quiet.py)
pyre_test_python_testcase(tests/journal.ext/chronicler_detail.py)
pyre_test_python_testcase(tests/journal.ext/chronicler_decor.py)
pyre_test_python_testcase(tests/journal.ext/cout.py)
pyre_test_python_testcase(tests/journal.ext/debug_cascade.py)
pyre_test_python_testcase(tests/journal.ext/debug_defaults.py)
pyre_test_python_testcase(tests/journal.ext/debug_empty.py)
pyre_test_python_testcase(tests/journal.ext/debug_example.py)
pyre_test_python_testcase(tests/journal.ext/debug_example_fatal.py)
pyre_test_python_testcase(tests/journal.ext/debug_file.py)
pyre_test_python_testcase(tests/journal.ext/debug_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/debug_flush.py)
pyre_test_python_testcase(tests/journal.ext/debug_inject.py)
pyre_test_python_testcase(tests/journal.ext/debug_instance.py)
pyre_test_python_testcase(tests/journal.ext/debug_loop.py)
pyre_test_python_testcase(tests/journal.ext/debug_notes.py)
pyre_test_python_testcase(tests/journal.ext/debug_properties.py)
pyre_test_python_testcase(tests/journal.ext/debug_quiet.py)
pyre_test_python_testcase(tests/journal.ext/debug_report.py)
pyre_test_python_testcase(tests/journal.ext/debug_sanity.py)
pyre_test_python_testcase(tests/journal.ext/debug_shared.py)
pyre_test_python_testcase(tests/journal.ext/device_init.py)
pyre_test_python_testcase(tests/journal.ext/entry_init.py)
pyre_test_python_testcase(tests/journal.ext/error_cascade.py)
pyre_test_python_testcase(tests/journal.ext/error_defaults.py)
pyre_test_python_testcase(tests/journal.ext/error_empty.py)
pyre_test_python_testcase(tests/journal.ext/error_example.py)
pyre_test_python_testcase(tests/journal.ext/error_example_nonfatal.py)
pyre_test_python_testcase(tests/journal.ext/error_file.py)
pyre_test_python_testcase(tests/journal.ext/error_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/error_flush.py)
pyre_test_python_testcase(tests/journal.ext/error_inject.py)
pyre_test_python_testcase(tests/journal.ext/error_instance.py)
pyre_test_python_testcase(tests/journal.ext/error_loop.py)
pyre_test_python_testcase(tests/journal.ext/error_notes.py)
pyre_test_python_testcase(tests/journal.ext/error_properties.py)
pyre_test_python_testcase(tests/journal.ext/error_quiet.py)
pyre_test_python_testcase(tests/journal.ext/error_report.py)
pyre_test_python_testcase(tests/journal.ext/error_sanity.py)
pyre_test_python_testcase(tests/journal.ext/error_shared.py)
pyre_test_python_testcase(tests/journal.ext/firewall_cascade.py)
pyre_test_python_testcase(tests/journal.ext/firewall_defaults.py)
pyre_test_python_testcase(tests/journal.ext/firewall_empty.py)
pyre_test_python_testcase(tests/journal.ext/firewall_example.py)
pyre_test_python_testcase(tests/journal.ext/firewall_example_nonfatal.py)
pyre_test_python_testcase(tests/journal.ext/firewall_file.py)
pyre_test_python_testcase(tests/journal.ext/firewall_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/firewall_flush.py)
pyre_test_python_testcase(tests/journal.ext/firewall_inject.py)
pyre_test_python_testcase(tests/journal.ext/firewall_instance.py)
pyre_test_python_testcase(tests/journal.ext/firewall_loop.py)
pyre_test_python_testcase(tests/journal.ext/firewall_notes.py)
pyre_test_python_testcase(tests/journal.ext/firewall_properties.py)
pyre_test_python_testcase(tests/journal.ext/firewall_quiet.py)
pyre_test_python_testcase(tests/journal.ext/firewall_report.py)
pyre_test_python_testcase(tests/journal.ext/firewall_sanity.py)
pyre_test_python_testcase(tests/journal.ext/firewall_shared.py)
pyre_test_python_testcase(tests/journal.ext/help_cascade.py)
pyre_test_python_testcase(tests/journal.ext/help_defaults.py)
pyre_test_python_testcase(tests/journal.ext/help_empty.py)
pyre_test_python_testcase(tests/journal.ext/help_example.py)
pyre_test_python_testcase(tests/journal.ext/help_example_fatal.py)
pyre_test_python_testcase(tests/journal.ext/help_file.py)
pyre_test_python_testcase(tests/journal.ext/help_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/help_flush.py)
pyre_test_python_testcase(tests/journal.ext/help_inject.py)
pyre_test_python_testcase(tests/journal.ext/help_instance.py)
pyre_test_python_testcase(tests/journal.ext/help_loop.py)
pyre_test_python_testcase(tests/journal.ext/help_notes.py)
pyre_test_python_testcase(tests/journal.ext/help_properties.py)
pyre_test_python_testcase(tests/journal.ext/help_quiet.py)
pyre_test_python_testcase(tests/journal.ext/help_report.py)
pyre_test_python_testcase(tests/journal.ext/help_sanity.py)
pyre_test_python_testcase(tests/journal.ext/help_shared.py)
pyre_test_python_testcase(tests/journal.ext/info_cascade.py)
pyre_test_python_testcase(tests/journal.ext/info_defaults.py)
pyre_test_python_testcase(tests/journal.ext/info_empty.py)
pyre_test_python_testcase(tests/journal.ext/info_example.py)
pyre_test_python_testcase(tests/journal.ext/info_example_fatal.py)
pyre_test_python_testcase(tests/journal.ext/info_file.py)
pyre_test_python_testcase(tests/journal.ext/info_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/info_flush.py)
pyre_test_python_testcase(tests/journal.ext/info_inject.py)
pyre_test_python_testcase(tests/journal.ext/info_instance.py)
pyre_test_python_testcase(tests/journal.ext/info_loop.py)
pyre_test_python_testcase(tests/journal.ext/info_notes.py)
pyre_test_python_testcase(tests/journal.ext/info_properties.py)
pyre_test_python_testcase(tests/journal.ext/info_quiet.py)
pyre_test_python_testcase(tests/journal.ext/info_report.py)
pyre_test_python_testcase(tests/journal.ext/info_sanity.py)
pyre_test_python_testcase(tests/journal.ext/info_shared.py)
pyre_test_python_testcase(tests/journal.ext/sanity.py)
pyre_test_python_testcase(tests/journal.ext/trash.py)
pyre_test_python_testcase(tests/journal.ext/warning_cascade.py)
pyre_test_python_testcase(tests/journal.ext/warning_defaults.py)
pyre_test_python_testcase(tests/journal.ext/warning_empty.py)
pyre_test_python_testcase(tests/journal.ext/warning_example.py)
pyre_test_python_testcase(tests/journal.ext/warning_example_fatal.py)
pyre_test_python_testcase(tests/journal.ext/warning_file.py)
pyre_test_python_testcase(tests/journal.ext/warning_file_mode.py)
pyre_test_python_testcase(tests/journal.ext/warning_flush.py)
pyre_test_python_testcase(tests/journal.ext/warning_inject.py)
pyre_test_python_testcase(tests/journal.ext/warning_instance.py)
pyre_test_python_testcase(tests/journal.ext/warning_loop.py)
pyre_test_python_testcase(tests/journal.ext/warning_notes.py)
pyre_test_python_testcase(tests/journal.ext/warning_properties.py)
pyre_test_python_testcase(tests/journal.ext/warning_quiet.py)
pyre_test_python_testcase(tests/journal.ext/warning_report.py)
pyre_test_python_testcase(tests/journal.ext/warning_sanity.py)
pyre_test_python_testcase(tests/journal.ext/warning_shared.py)

# the drivers leave their scratch products behind so they can be inspected; sweep them
pyre_test_python_cleanup(api_file.log tests/journal.ext/api_file.py)
pyre_test_python_cleanup(debug_file.log tests/journal.ext/debug_file.py)
pyre_test_python_cleanup(error_file.log tests/journal.ext/error_file.py)
pyre_test_python_cleanup(firewall_file.log tests/journal.ext/firewall_file.py)
pyre_test_python_cleanup(help_file.log tests/journal.ext/help_file.py)
pyre_test_python_cleanup(info_file.log tests/journal.ext/info_file.py)
pyre_test_python_cleanup(warning_file.log tests/journal.ext/warning_file.py)
pyre_test_python_cleanup(api_file_mode.log tests/journal.ext/api_file_mode.py)
pyre_test_python_cleanup(debug_file_mode.log tests/journal.ext/debug_file_mode.py)
pyre_test_python_cleanup(error_file_mode.log tests/journal.ext/error_file_mode.py)
pyre_test_python_cleanup(firewall_file_mode.log tests/journal.ext/firewall_file_mode.py)
pyre_test_python_cleanup(help_file_mode.log tests/journal.ext/help_file_mode.py)
pyre_test_python_cleanup(info_file_mode.log tests/journal.ext/info_file_mode.py)
pyre_test_python_cleanup(warning_file_mode.log tests/journal.ext/warning_file_mode.py)

# end of file
