# -*- cmake -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


#
# journal
#
pyre_test_python_testcase(tests/journal.pkg/alert_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/alert_long_filename.py)
pyre_test_python_testcase(tests/journal.pkg/boot_device.py)
pyre_test_python_testcase(tests/journal.pkg/boot_handoff.py)
pyre_test_python_testcase(tests/journal.pkg/ansi_ansi.py)
pyre_test_python_testcase_env(tests/journal.pkg/ansi_emulates.py "TERM=foo" 0)
pyre_test_python_testcase_env(tests/journal.pkg/ansi_emulates.py "TERM=xterm" 1)
pyre_test_python_testcase(tests/journal.pkg/ansi_gray.py)
pyre_test_python_testcase(tests/journal.pkg/ansi_misc.py)
pyre_test_python_testcase(tests/journal.pkg/ansi_null.py)
pyre_test_python_testcase(tests/journal.pkg/ansi_x11.py)
pyre_test_python_testcase(tests/journal.pkg/api_application.py)
pyre_test_python_testcase(tests/journal.pkg/api_file.py)
pyre_test_python_testcase(tests/journal.pkg/api_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/api_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/bland_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/cerr_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/channel_default_device.py)
pyre_test_python_testcase(tests/journal.pkg/channel_device.py)
pyre_test_python_testcase(tests/journal.pkg/channel_index.py)
pyre_test_python_testcase(tests/journal.pkg/channel_inject.py)
pyre_test_python_testcase(tests/journal.pkg/channel_inventory.py)
pyre_test_python_testcase(tests/journal.pkg/channel_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/channel_state.py)
pyre_test_python_testcase(tests/journal.pkg/channel_twice.py)
pyre_test_python_testcase(tests/journal.pkg/channel_xtalk.py)
pyre_test_python_testcase(tests/journal.pkg/chronicler_device.py)
pyre_test_python_testcase(tests/journal.pkg/chronicler_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/courier_closed.py)
pyre_test_python_testcase(tests/journal.pkg/courier_full.py)
pyre_test_python_testcase(tests/journal.pkg/courier_mirror.py)
pyre_test_python_testcase(tests/journal.pkg/courier_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/courier_ship.py)
pyre_test_python_testcase(tests/journal.pkg/cout_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/csi_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/debug_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/debug_empty.py)
pyre_test_python_testcase(tests/journal.pkg/debug_example.py)
pyre_test_python_testcase(tests/journal.pkg/debug_example_fatal.py)
pyre_test_python_testcase(tests/journal.pkg/debug_file.py)
pyre_test_python_testcase(tests/journal.pkg/debug_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/debug_flush.py)
pyre_test_python_testcase(tests/journal.pkg/debug_inject.py)
pyre_test_python_testcase(tests/journal.pkg/debug_instance.py)
pyre_test_python_testcase(tests/journal.pkg/debug_loop.py)
pyre_test_python_testcase(tests/journal.pkg/debug_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/debug_report.py)
pyre_test_python_testcase(tests/journal.pkg/debug_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/error_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/error_empty.py)
pyre_test_python_testcase(tests/journal.pkg/error_example.py)
pyre_test_python_testcase(tests/journal.pkg/error_example_nonfatal.py)
pyre_test_python_testcase(tests/journal.pkg/error_file.py)
pyre_test_python_testcase(tests/journal.pkg/error_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/error_flush.py)
pyre_test_python_testcase(tests/journal.pkg/error_inject.py)
pyre_test_python_testcase(tests/journal.pkg/error_instance.py)
pyre_test_python_testcase(tests/journal.pkg/error_loop.py)
pyre_test_python_testcase(tests/journal.pkg/error_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/error_report.py)
pyre_test_python_testcase(tests/journal.pkg/error_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/file_example.py)
pyre_test_python_testcase(tests/journal.pkg/file_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_empty.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_example.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_example_nonfatal.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_file.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_flush.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_inject.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_instance.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_loop.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_report.py)
pyre_test_python_testcase(tests/journal.pkg/firewall_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/index_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/index_lookup.py)
pyre_test_python_testcase(tests/journal.pkg/index_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/help_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/help_empty.py)
pyre_test_python_testcase(tests/journal.pkg/help_example.py)
pyre_test_python_testcase(tests/journal.pkg/help_example_fatal.py)
pyre_test_python_testcase(tests/journal.pkg/help_file.py)
pyre_test_python_testcase(tests/journal.pkg/help_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/help_flush.py)
pyre_test_python_testcase(tests/journal.pkg/help_inject.py)
pyre_test_python_testcase(tests/journal.pkg/help_instance.py)
pyre_test_python_testcase(tests/journal.pkg/help_loop.py)
pyre_test_python_testcase(tests/journal.pkg/help_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/help_report.py)
pyre_test_python_testcase(tests/journal.pkg/help_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/info_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/info_empty.py)
pyre_test_python_testcase(tests/journal.pkg/info_example.py)
pyre_test_python_testcase(tests/journal.pkg/info_example_fatal.py)
pyre_test_python_testcase(tests/journal.pkg/info_file.py)
pyre_test_python_testcase(tests/journal.pkg/info_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/info_flush.py)
pyre_test_python_testcase(tests/journal.pkg/info_inject.py)
pyre_test_python_testcase(tests/journal.pkg/info_instance.py)
pyre_test_python_testcase(tests/journal.pkg/info_loop.py)
pyre_test_python_testcase(tests/journal.pkg/info_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/info_report.py)
pyre_test_python_testcase(tests/journal.pkg/info_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/memo_long_filename.py)
pyre_test_python_testcase(tests/journal.pkg/memo_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/null_inject.py)
pyre_test_python_testcase(tests/journal.pkg/null_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/record_decode.py)
pyre_test_python_testcase(tests/journal.pkg/record_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/sanity.py)
pyre_test_python_testcase(tests/journal.pkg/trash_sanity.py)
pyre_test_python_testcase(tests/journal.pkg/warning_cascade.py)
pyre_test_python_testcase(tests/journal.pkg/warning_empty.py)
pyre_test_python_testcase(tests/journal.pkg/warning_example.py)
pyre_test_python_testcase(tests/journal.pkg/warning_example_fatal.py)
pyre_test_python_testcase(tests/journal.pkg/warning_file.py)
pyre_test_python_testcase(tests/journal.pkg/warning_file_mode.py)
pyre_test_python_testcase(tests/journal.pkg/warning_flush.py)
pyre_test_python_testcase(tests/journal.pkg/warning_inject.py)
pyre_test_python_testcase(tests/journal.pkg/warning_instance.py)
pyre_test_python_testcase(tests/journal.pkg/warning_loop.py)
pyre_test_python_testcase(tests/journal.pkg/warning_quiet.py)
pyre_test_python_testcase(tests/journal.pkg/warning_report.py)
pyre_test_python_testcase(tests/journal.pkg/warning_sanity.py)

# the drivers leave their scratch products behind so they can be inspected; sweep them
pyre_test_python_cleanup(api_file.log tests/journal.pkg/api_file.py)
pyre_test_python_cleanup(debug_file.log tests/journal.pkg/debug_file.py)
pyre_test_python_cleanup(error_file.log tests/journal.pkg/error_file.py)
pyre_test_python_cleanup(firewall_file.log tests/journal.pkg/firewall_file.py)
pyre_test_python_cleanup(help_file.log tests/journal.pkg/help_file.py)
pyre_test_python_cleanup(info_file.log tests/journal.pkg/info_file.py)
pyre_test_python_cleanup(warning_file.log tests/journal.pkg/warning_file.py)
pyre_test_python_cleanup(file_sanity.log tests/journal.pkg/file_sanity.py)
pyre_test_python_cleanup(file_example.log tests/journal.pkg/file_example.py)
pyre_test_python_cleanup(api_file_mode.log tests/journal.pkg/api_file_mode.py)
pyre_test_python_cleanup(debug_file_mode.log tests/journal.pkg/debug_file_mode.py)
pyre_test_python_cleanup(error_file_mode.log tests/journal.pkg/error_file_mode.py)
pyre_test_python_cleanup(firewall_file_mode.log tests/journal.pkg/firewall_file_mode.py)
pyre_test_python_cleanup(help_file_mode.log tests/journal.pkg/help_file_mode.py)
pyre_test_python_cleanup(info_file_mode.log tests/journal.pkg/info_file_mode.py)
pyre_test_python_cleanup(warning_file_mode.log tests/journal.pkg/warning_file_mode.py)


# end of file
