# -*- yaml -*-
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2021 all rights reserved

name: mm
on: push
jobs:
  # build and test the HEAD of the repository
  build:
    name: ${{matrix.target}} python-${{matrix.python}},${{matrix.suite}}-${{matrix.suiteVersion}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        # target: [debug, opt]
        # python: [3.8, 3.9]
        target: [debug]
        python: [3.9]
        suite: [clang, gcc]
        suiteVersion: [ 9, 10, 11, 12]
        exclude:
          - suite: gcc
            suiteVersion: 12
          - suite: gcc
            suiteVersion: 11
          - suite: clang
            suiteVersion: 9

    steps:
      - name: ${{matrix.os}} refresh
        run: |
          echo " -- update the package cache"
          sudo apt update
          echo " -- upgradables"
          sudo apt list --upgradable
          echo " -- upgrade"
          sudo apt dist-upgrade
          echo " -- install our dependencies"
          sudo apt install -y make openssh-server libgsl-dev libopenmpi-dev

      - name: python ${{matrix.python}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install graphene numpy pybind11 PyYAML

      - name: list system packages
        run: |
          dpkg -l

      - name: versions
        run: |
          echo " -- make"
          make --version
          echo " -- python"
          python3 --version
          echo " -- ${{matrix.suite}}"
          ${{matrix.suite}}-${{matrix.suiteVersion}} --version

      - name: locations
        run: |
          echo " -- graphene"
          pip3 show graphene
          echo " -- numpy"
          pip3 show numpy
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/numpy/core/include
          echo " -- pybind11"
          pip3 show pybind11
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/pybind11/include
          echo " -- yaml"
          pip3 show PyYAML
        env:
          pythonVersion: ${{matrix.python}}

      - name: clone
        run: |
         echo " -- cloning mm"
         git clone https://github.com/aivazis/mm
         echo " -- cloning pyre"
         git clone https://github.com/pyre/pyre

      - name: build pyre
        run: |
          echo " -- aliasing mm"
          export MM="python3 ${PWD}/mm/mm.py --make=make --runcfg=.github/matrix"
          echo mm: ${MM}
          ${MM} --help
          echo " -- switching to the pyre home directory"
          cd pyre
          echo " -- checking out the correct ref"
          git checkout ${GITHUB_SHA}
          echo " -- checking whether mm can run from here"
          echo now at: ${PWD}
          ${MM} host.info
          ${MM} builder.info
          ${MM} make.info
          echo " -- verifying external packages"
          ${MM} extern.gsl.info
          ${MM} extern.mpi.info
          ${MM} extern.numpy.info
          ${MM} extern.pybind11.info
          echo " -- building pyre"
          ${MM}
          echo " -- testing pyre"
          ${MM} tests
        env:
          pythonVersion: ${{matrix.python}}

# end of file
