# -*- yaml -*-
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2021 all rights reserved

name: mm
on: push
jobs:
  # build and test the HEAD of the repository
  build:
    name: ${{matrix.os}} + python ${{matrix.python}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.8, 3.9]

    steps:
      - name: ${{matrix.os}} refresh
        run: |
          echo " -- update the package cache"
          sudo apt update
          echo " -- upgradables"
          sudo apt list --upgradable
          echo " -- upgrade"
          sudo apt dist-upgrade
          echo " -- install our dependencies"
          sudo apt install -y make openssh-server libgsl-dev libopenmpi-dev

      - name: python ${{matrix.python}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install graphene numpy pybind11 PyYAML

      - name: list system packages
        run: |
          dpkg -l

      - name: versions
        run: |
          echo " -- make"
          make --version
          echo " -- python"
          python3 --version

      - name: locations
        run: |
          echo " -- graphene"
          pip3 show graphene
          echo " -- numpy"
          pip3 show numpy
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/numpy/core/include
          echo " -- pybind11"
          pip3 show pybind11
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/pybind11/include
          echo " -- yaml"
          pip3 show PyYAML
        env:
          pythonVersion: ${{matrix.python}}

      - name: clone
        run: |
         echo " -- cloning mm"
         git clone git@github.com:aivazis/mm
         echo " -- cloning pyre"
         git clone git@github.com:pyre/pyre

# end of file
