# -*- yaml -*-
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2021 all rights reserved


name: notify
on: [push]
jobs:

  # notify my CI server
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: repo info
        run: "echo repository: ${GITHUB_REPOSITORY}"
      - name: graphql API
        run: "echo event: ${GITHUB_GRAPHQL_URL}"
      - name: event info
        run: "echo event: ${GITHUB_EVENT_NAME}"
      - name: commit info
        run: "echo sha: ${GITHUB_SHA}, ref: ${GITHUB_REF}"
      - name: runner info
        run: "echo ${RUNNER_OS}"
      - name: runner packages
        run: "dpkg -l"
      - name: runner cache location
        run: "echo ${RUNNER_TOOL_CACHE}"
      - name: node cache contents
        run: "ls -l ${RUNNER_TOOL_CACHE}/node"
      - name: python cache contents
        run: "ls -l ${RUNNER_TOOL_CACHE}/Python"
      - name: python 3.9.5 cache contents
        run: "find ${RUNNER_TOOL_CACHE}/Python/3.9.5"
      - name: wget
        run: wget --version
      - name: curl
        run: curl --version
      - name: cwd
        run: find .
      - name: home
        run: "echo ~; find ~"
      - name: clone mm
        run: git clone https://github.com/aivazis/mm
      - name: cwd after mm cloning
        run: find .


# end of file