name: pr-pypi

# publish when a (published) GitHub Release is created, use the following:
on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        python: [cp311]

    steps:
      - uses: actions/checkout@v3

      - name: build wheels
        uses: pypa/cibuildwheel@v2.16.1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
