name: pypi-wheels

# publish when a (published) GitHub Release is created, use the following:
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11]
        python: [cp38, cp39, cp310, cp311]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4

      - name: install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.1

      - name: build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: pyre-wheels
          path: wheelhouse/

  upload:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyre
    permissions:
      id-token: write
    # publish when a GitHub Release is created, use the following rule:
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: pyre-wheels
          path: wheelhouse/

      - uses: pypa/gh-action-pypi-publish@release/v1
