name: pypi-wheels

# publish when a (published) GitHub Release is created, use the following:
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: build ${{ matrix.python }} wheel on ${{ matrix.platforms[1] }}
    runs-on: ${{ matrix.platforms[0] }}
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - [ubuntu-20.04, manylinux_x86_64]
          - [macos-12, macosx_x86_64]
          # - [macos-12, macosx_arm64]
        python: [cp39, cp310, cp311, cp312]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platforms[1] }}
          CIBW_SKIP: pp*

      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: pyre-wheels
          path: wheelhouse/

  upload:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyre
    permissions:
      id-token: write
    # publish only when a GitHub release is created
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: pyre-wheels
          path: wheelhouse/

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: wheelhouse/
